site:
  start_page: home::index.adoc
  title: PortX Documentation
  url: https://port.io

content:
  sources:
  
  - url: https://github.com/modusintegration/docs-playbook.git 
    branches: master
    start_path: home
    
  - url: https://github.com/modusintegration/modusbox-docs.git 
    branches: [master, new-mule]
    start_path: partner-manager
    
  - url: https://github.com/modusintegration/modusbox-docs.git 
    branches: [master, new-mule] 
    start_path: partner-manager-connector
 
  - url: https://github.com/modusintegration/modusbox-docs.git 
    branches: [master, new-mule] 
    start_path: release-notes
    
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    linkattrs: ''

output:
  destinations:
  - provider: fs
    path: build/site
    clean: true
ui:
  bundle:
    url: ./../antora-ui/build/ui-bundle.zip
    snapshot: true
runtime:
  pull: true