site:
  start_page: portx::index.adoc
  title: PortX Documentation
  url: https://modusbox-docs.s3-website-us-west-2.amazonaws.com/portx/index.html
content:
  sources:

  - url: https://github.com/modusintegration/modusbox-docs.git 
    branches: dev 
    start_path: portx
  - url: https://github.com/modusintegration/modusbox-docs.git 
    branches: dev 
    start_path: partner-manager
  - url: https://github.com/modusintegration/modusbox-docs.git 
    branches: dev 
    start_path: partner-manager-connector
  - url: https://github.com/modusintegration/modusbox-docs.git 
    branches: dev 
    start_path: release-notes
    


output:
  destinations:
  - provider: fs
    path: build/site
    clean: true
ui:
  bundle:
    url: ./../antora-ui/build/ui-bundle.zip
    snapshot: true
runtime:
  pull: true